//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MakeTheExtranetGreatAgain.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TheBDDEntities : DbContext
    {
        public TheBDDEntities()
            : base("name=TheBDDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Activites> Activites { get; set; }
        public virtual DbSet<Cours> Cours { get; set; }
        public virtual DbSet<Doc_Web> Doc_Web { get; set; }
        public virtual DbSet<Groupes> Groupes { get; set; }
        public virtual DbSet<Individus> Individus { get; set; }
        public virtual DbSet<Messages> Messages { get; set; }
        public virtual DbSet<Options_Questionnaire> Options_Questionnaire { get; set; }
        public virtual DbSet<Questionnaires> Questionnaires { get; set; }
        public virtual DbSet<Salles> Salles { get; set; }
        public virtual DbSet<Sous_doc_Web> Sous_doc_Web { get; set; }
        public virtual DbSet<Statut> Statut { get; set; }
        public virtual DbSet<Tâches> Tâches { get; set; }
        public virtual DbSet<Types_Questionnaire> Types_Questionnaire { get; set; }
        public virtual DbSet<Creneaux> Creneaux { get; set; }
    }
}
