//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularJS_CS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MainDBEntities4 : DbContext
    {
        public MainDBEntities4()
            : base("name=MainDBEntities4")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Activite> Activite { get; set; }
        public virtual DbSet<Cours> Cours { get; set; }
        public virtual DbSet<Doc_Web> Doc_Web { get; set; }
        public virtual DbSet<Groupe> Groupe { get; set; }
        public virtual DbSet<Individu> Individu { get; set; }
        public virtual DbSet<Message> Message { get; set; }
        public virtual DbSet<Option_Questionnaire> Option_Questionnaire { get; set; }
        public virtual DbSet<Questionnaire> Questionnaire { get; set; }
        public virtual DbSet<Salle> Salle { get; set; }
        public virtual DbSet<Sous_doc_Web> Sous_doc_Web { get; set; }
        public virtual DbSet<Statut> Statut { get; set; }
        public virtual DbSet<Tâche> Tâche { get; set; }
        public virtual DbSet<Type_Questionnaire> Type_Questionnaire { get; set; }
        public virtual DbSet<Creneau> Creneau { get; set; }
    }
}
