//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularJS_CS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Questionnaires
    {
        public int Id { get; set; }
        public int Id_message { get; set; }
        public int Id_Option { get; set; }
        public string type { get; set; }
    
        public virtual Messages Messages { get; set; }
        public virtual Options_Questionnaire Options_Questionnaire { get; set; }
        public virtual Types_Questionnaire Types_Questionnaire { get; set; }
    }
}
