//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularJS_CS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Questionnaire
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Questionnaire()
        {
            this.Option_Questionnaire = new HashSet<Option_Questionnaire>();
        }
    
        public int Id { get; set; }
        public int Id_message { get; set; }
        public int type { get; set; }
        public Nullable<int> Id_rep { get; set; }
    
        public virtual Message Message { get; set; }
        public virtual Type_Questionnaire Type_Questionnaire { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Option_Questionnaire> Option_Questionnaire { get; set; }
        public virtual Option_Questionnaire Option_Questionnaire1 { get; set; }
    }
}
